version: "3"

services:

  app:
  #   image: https://mydomainname.com/my-docker-registry/reponame:latest
    build:
      dockerfile: docker-build/app/Dockerfile
      context: ./
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+pg8000://username:${POSTGRES_PASSWORD}@pg:5432/blog
      CONFIG_NAME: ProductionConfig
    ports:
      - "1080:80"


  pg:
    image: postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: username
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata

  pgadmin:
    image: "dpage/pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD:  ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"

volumes:
  pgadmin:
  db-data:
